### ISSUE TITLE
Ask about mechanical modeling in paper

### ISSUE THREAD

**Issue by L-SY** [utiasDSL/upright#9]
Dear Adam Heins:
  I'd like to ask some questions about mechanical modeling.
![32105f790f03e6da6b635ff034a03b7](https://github.com/user-attachments/assets/544b7e22-f6ca-4863-9ef8-e2d5c0f8d099)
Is this equation in the Ee coordinate system？ In the Body frame, Fext is not zero because the object on Ee has velocity and acceleration.

![78c5b7bfd9356c992b338c2ad44833d](https://github.com/user-attachments/assets/44ea5883-870d-474b-87b6-70a90888195f)
How did you come up with this expression?
I don't have a good understanding of mechanics, and I hope I can get your answer.

It seems to me that F_GI is a minus sign equal to Fc, because in the Body frame: 
$F_C + F_{GI} = ma$
So $F_{GI} =-(ma- F_{GI})$
The origin of $T_{GI}$ is because Fc does not provide Tau to objects?

Hope to get your reply！
Thanks！

**Comment by adamheins** [comment]
For the first equation, it doesn't actually matter which frame it's in (being satisfied in one frame means it is satisfied in all others). In the paper it turns out to be convenient to represent it in the body frame, which is the representation for the second equation.

The second equation is the gravito-inertial wrench: the gravito-inertial force is just mass x acceleration minus gravitational force (rotated into the body frame). The torque is just the inertial torque. This is really just the Newton-Euler equations of motion for rigid bodies.

Your interpretation at the bottom is not quite correct. $ma$ is already part of the gravito-inertial force $f_{GI}$:
$f_{C} + f_{GI} = 0$
$f_{GI} = -(ma - mg)$

**Comment by L-SY** [comment]
Thank you very much for your answer.
    I still have some doubts about the first point. In the world  frame (ground  frame), the object has its own velocity and acceleration, but doesn't the first equation mean that it remains stationary or in a uniform straight line with zero external force.

**Comment by adamheins** [comment]
The external forces acting on the system are the contact forces (contained in $w_C$) and gravity (contained in $w_{GI}$). This is true in the body frame and in the world frame. Depending on the contact forces, the object can certainly accelerate and/or rotate.
